Add multiple read from view
rhinoman/couchdb-go pull request #9
Opened 2017-06-11 20:29 UTC by mffrench

Hello,

I added a function to read a view with a POST and an array of keys.

Let me know what you think.

Cheers,

2017-06-12 03:21 UTC, rhinoman commented on couchdb.go
> +func (db *Database) GetMutipleFromView(designDoc string, view string,
Should be GetMultipleFromView

2017-06-12 03:23 UTC, rhinoman requested changes
Looks good, just need to correct the spelling of the function name.  Thanks!

2017-06-14 06:59 UTC, mffrench commented on couchdb.go
> +func (db *Database) GetMutipleFromView(designDoc string, view string,
yeah you right ! will do that asap :)

2017-06-20 10:22 UTC, mffrench commented
Just solved spelling issue...

2017-06-21 03:30 UTC, rhinoman approved these changes
Thanks

2017-06-21 03:30 UTC, merged